### PR TITLE
Associate skills that spawn something via NewNpcSummon

### PR DESCRIPTION
**Pull request by Henjuro**
I am not really sure if there is other things that trigger this OpCode, I could not find anything else.
Should fix Issue #19

### CODE REVIEW

**Comment by Iuke121** [comment]
Are we sure the owner id is in byte position 0?

**Comment by Henjuro** [comment]
I looked at the values in it and for multiple instances and they seemed to be in bytes starting at pos 0. I am not sure how many bytes through, but since they seem to be assumed to be 64bit in all other cases, I went with that here.

**Comment by Iuke121** [comment]
> I looked at the values in it for multiple instances and they seemed to be in bytes starting at pos 0. I am not sure how many bytes through, but since they seem to be assumed to be 64bit in all other cases, I went with that here.

That's interesting, the result was that the damage showed up, but under a separate entity. I didn't get a chance to look at it too much though.

**Comment by shalzuth** [comment]
if these didn't change every patch, i'd ask if you could include a sample packet...

**Comment by Iuke121** [comment]
@Henjuro are you on the discord?

**Pull request merged**
