### PR TITLE
Death counter

### PR DESCRIPTION
**Pull request by cwhavener**
Added death counter. currently Is hard coded to only count the first 2 deaths of every encounter. Death count is reset on raid end, but not raid wipe or boss death. (for example death count will not reset for every attempted valton pull, only a raid disband or completion)

### CODE REVIEW

**Comment by shalzuth** [comment]
why is there a max of 2?

**Comment by cwhavener** [comment]
Max of two currently because only the first 1-4ish deaths in a pull really matter. If  I counted all deaths then each failed pull everyone would get a death which doesn't give us any info

**Comment by cwhavener** [comment]
if your the last alive it wont count it as a death because your death didnt matter

**Comment by shalzuth** [comment]
Can you remove that? And then the GUI could filter instead? We want to log all deaths

**Comment by cwhavener** [comment]
Ok its now logging all deaths to the.log file, if that's what you meant. Still only displaying the first two deaths on the GUI

**Pull request closed without merging**
