### PR TITLE
ElectronBridge launch parameter support

### PR DESCRIPTION
**Pull request by karaeren**
Adds launch parameter support and winpcap support to the ElectronBridge. Also removed Console.WriteLine's that can break electron connection.

I think we should create a logger class that logs on debug mode and writes to a logfile on prod.

### CODE REVIEW

**Comment by noita-player** [comment]
is there a reason 9f01abd removes exception spew that can be used to understand why winpcap failed to load? does your electronbridge hijack stdout?

**Comment by karaeren** [comment]
> is there a reason [9f01abd](https://github.com/shalzuth/LostArkLogger/commit/9f01abd049cd4ec53f09a83231c60195a16b942f) removes exception spew that can be used to understand why winpcap failed to load? does your electronbridge hijack stdout?

Bridge connection on node side only expects json outputs and it breaks. That's why I suggested a logger. This console.writeline's are definitely not the way to go and they are not visible to the users anyway.

**Comment by noita-player** [comment]
Since the contract isn't well defined, I'd recommend setting up a named pipe and writing your messages to/from that pipe, so they don't get screwed by other things that may end up on stdout. Either way, we do need #63 - I haven't started any work on it.

**Comment by shalzuth** [comment]
The plan is to use console output more for debugability and triage, please fix this on the electron side instead.

**Comment by karaeren** [comment]
> The plan is to use console output more for debugability and triage, please fix this on the electron side instead.

I won't be adding the console statements back as they are pretty much debugging only and completely break the workflow of the electron app.

**Pull request closed without merging**
