### PR TITLE
added damage details window when clicking on player damage bar

### PR DESCRIPTION
**Pull request by shnok**
show damage details in a popup window 
[Preview](https://imgur.com/a/OxcROZw)

### CODE REVIEW

**Comment by shalzuth** [comment]
To match other dps windows, usually on click, it changes the current window, not spawning a new one. Can you edit it for that instead?

If not, can we keep a single form and reuse that single form class? I don't have want to duplicate code. Otherwise we'll have a new class for each new thing we want, heals, buffs, stagger, etc.

**Comment by shnok** [comment]
> To match other dps windows, usually on click, it changes the current window, not spawning a new one. Can you edit it for that instead?
> 
> If not, can we keep a single form and reuse that single form class? I don't have want to duplicate code. Otherwise we'll have a new class for each new thing we want, heals, buffs, stagger, etc.

Sure it's possible, I'll look into that

**Comment by shnok** [comment]
Now you can switch between the two types with left and right clics

**Comment by shalzuth** [comment]
Thanks! This looks good for 2 swaps, but we might need a state machine or something in the future, for when you swap between heals, buffs, etc

**Pull request merged**
